// Centralized route segments for easier lookup and debugging
export const ROUTE_SEGMENTS = {
    ROOT: "/",
    CONTRACTS: "contracts",
    WALLET: "wallet",
    LAW: "law",
    TRANSACTIONS: "transactions",
    MEDICINE: "medicine",
    GAMING: "gaming",
    FINANCE: "finance",
}

const ROOT = ROUTE_SEGMENTS.ROOT
const CONTRACTS = `/${ROUTE_SEGMENTS.CONTRACTS}`
const WALLET = `/${ROUTE_SEGMENTS.CONTRACTS}/${ROUTE_SEGMENTS.WALLET}`
const LAW = `/${ROUTE_SEGMENTS.CONTRACTS}/${ROUTE_SEGMENTS.LAW}`
const TRANSACTIONS = `/${ROUTE_SEGMENTS.CONTRACTS}/${ROUTE_SEGMENTS.TRANSACTIONS}`
const MEDICINE = `/${ROUTE_SEGMENTS.CONTRACTS}/${ROUTE_SEGMENTS.MEDICINE}`
const GAMING = `/${ROUTE_SEGMENTS.CONTRACTS}/${ROUTE_SEGMENTS.GAMING}`
const FINANCE = `/${ROUTE_SEGMENTS.CONTRACTS}/${ROUTE_SEGMENTS.FINANCE}`

export const ROUTES = {
    ROOT,
    CONTRACTS,
    WALLET,
    LAW,
    TRANSACTIONS,
    MEDICINE,
    GAMING,
    FINANCE,
}
